import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";
import Layout from "@/components/Layout/Layout";
import ReactQueryProvider from "@/config/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark`}>
        <ReactQueryProvider>
          <HeroUIProvider>
            <Layout>{children}</Layout>
          </HeroUIProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
